### ISSUE TITLE
integration not working anymore #2

### ISSUE THREAD

**Issue by Drakalinou** [RobertD502/home-assistant-lavviebot#10]
Hello, same as before https://github.com/RobertD502/home-assistant-lavviebot/issues/5

Since few weeks now, not sure if it's just me or not ? 

Thanks

**Comment by RobertD502** [comment]
Are you running the latest version (0.3.0)?

Also, sorry just saw that you commented on the last issue ~1 month ago - I never got a notification.

**Comment by RobertD502** [comment]
@Drakalinou 

I'm assuming it is working as expected when on version 0.3.0 - I haven't had any issues on two separate purrsong accounts/homes. If not, please add any extra details.
