### ISSUE TITLE
You have been rate limited by the Purrsong API. Decrease the polling frequency or create a new ClientSession

### ISSUE THREAD

**Issue by Drakalinou** [RobertD502/home-assistant-lavviebot#11]
Hi, 

it's been few weeks now, i'm being limited by the purrsong API so my devices are always "unaviable" 

If i turn off the plugin for a while the restriction goes away, they probably updated their API to limit the number of connections... Is there a way to adjust the polling frequency ? Even if it's just few times a day it's good to have the infos 

Thanks ! 
[home-assistant_purrsong_2024-12-02T08-12-43.290Z.log](https://github.com/user-attachments/files/17974882/home-assistant_purrsong_2024-12-02T08-12-43.290Z.log)

**Comment by RobertD502** [comment]
Hi. Disable the integration for ~24 hours. This should get the rate limit to reset.
Also, open the `const.py` file located in the `custom_components/purrsong/` directory and change the `DEFAULT_SCAN_INTERVAL` to `90`. Based on my personal testing, I have avoided rate limits once polling frequency was changed to every 90 seconds.

**Comment by RobertD502** [comment]
Release `0.3.2` includes the new 90 second update interval. Disabling the integration to get the initial rate limit to drop off still applies.
