### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by PedroCPereiraDev** [RobertD502/home-assistant-lavviebot#2]
Hello,
When trying to configure the integration, I am receiving the following error: "LavvieBot authentication failed. Are your credentials correct?"

I have tried with my email and with my username and it always fails.

**Comment by RobertD502** [comment]
As of about a day or so ago, the lavviebot creators have released a new app and killed the old API endpoints which this integration relies on. I will need to reverse engineer their new app to get the new endpoints and rewrite the backend that this integration uses. Until then, this integration won't work.

**Comment by RobertD502** [comment]
Fixed with `0.1.0` release
