### ISSUE TITLE
Fail error, new try, looping

### ISSUE THREAD

**Issue by Arekisu63** [RobertD502/home-assistant-lavviebot#3]
Followed all instructions, but no entities found, tooltip says "object does not support item assignment"

here is the log :

2023-10-23 18:56:12.625 ERROR (MainThread) [custom_components.purrsong] Unexpected error fetching purrsong data: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/purrsong/coordinator.py", line 45, in _async_update_data
    data = await self.client.async_get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lavviebot/lavviebot_client.py", line 292, in async_get_data
    selected_cat['is_unknown'] = False
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

**Comment by RobertD502** [comment]
If you wouldn't mind, add me as a family member within the purrsong app: Hit the gear icon in the upper right-hand corner, click on Add user, select Family, and for email enter githubpurrsong @ gmail.com (without the spaces before/after @ sign).

I'll need to investigate what is going on specifically with your cat list.

**Comment by Arekisu63** [comment]
Thank you Robert. I added you. Welcome to my familly :D. I performed a firmware update to rule that out.

**Comment by RobertD502** [comment]
@Arekisu63 The issue has been fixed. Turns out that shared accounts, by default, have a `Home` location that has no cats, which was causing the issue. The backend has been fixed to account for this.

New version (`0.1.10`) has been released which should fix your issue.

I've also gone ahead and removed the githubpurrsong user from your family account.

**Comment by Arekisu63** [comment]
Thank you !

Indeed it works 



Le 24 octobre 2023 19:19:24 GMT+02:00, "Dr. Drinovac" ***@***.***> a écrit :
